# Generated by Django 6.0.2 on 2026-02-12 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fooditem',
            old_name='carbs',
            new_name='glucides',
        ),
        migrations.RenameField(
            model_name='fooditem',
            old_name='fat',
            new_name='lipides',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='target_carbs',
            new_name='target_glucides',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='target_fat',
            new_name='target_lipides',
        ),
    ]
