# Generated by Django 6.0.2 on 2026-02-12 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_rename_carbs_fooditem_glucides_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealentry',
            name='total_carbs',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='mealentry',
            name='total_fat',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='mealentry',
            name='total_protein',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='mealentry',
            name='total_kcal',
            field=models.IntegerField(default=0),
        ),
    ]
