# Generated by Django 6.0.2 on 2026-02-12 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_mealentry_total_carbs_mealentry_total_fat_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mealentry',
            old_name='total_carbs',
            new_name='total_glucides',
        ),
        migrations.RenameField(
            model_name='mealentry',
            old_name='total_fat',
            new_name='total_lipides',
        ),
    ]
