# Generated by Django 6.0.2 on 2026-02-12 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_rename_total_carbs_mealentry_total_glucides_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='target_protein',
            new_name='target_proteins',
        ),
    ]
