# Generated by Django 6.0.2 on 2026-02-12 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_rename_target_protein_profile_target_proteins'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fooditem',
            old_name='protein',
            new_name='proteins',
        ),
        migrations.RenameField(
            model_name='mealentry',
            old_name='total_protein',
            new_name='total_proteins',
        ),
    ]
